<a href="https://colab.research.google.com/github/sonjoy1s/Deep-Learning/blob/main/Diabetes_Risk_Prediction_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("/content/diabetes_risk_dataset.csv")
df.head()

,Patient_ID,age,gender,bmi,blood_pressure,fasting_glucose_level,insulin_level,HbA1c_level,cholesterol_level,triglycerides_level,physical_activity_level,daily_calorie_intake,sugar_intake_grams_per_day,sleep_hours,stress_level,family_history_diabetes,waist_circumference_cm,diabetes_risk_score,diabetes_risk_category
0,1,77,Female,33.8,154,93,12.1,5.2,242,194,Low,2169,78.4,8.1,4,No,101.1,52.3,Prediabetes
1,2,54,Male,19.2,123,94,4.6,5.4,212,76,High,1881,16.5,6.6,3,No,60.0,3.7,Low Risk
2,3,25,Male,33.7,141,150,10.8,6.9,247,221,Low,2811,147.9,6.7,10,Yes,114.7,87.3,High Risk
3,4,23,Female,32.8,140,145,11.6,6.8,195,193,Low,2826,98.3,4.4,9,Yes,96.6,76.1,High Risk
4,5,70,Male,33.7,165,90,18.3,5.6,217,170,Moderate,2610,65.8,9.1,5,Yes,107.4,47.7,Prediabetes

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6000 entries, 0 to 5999
Data columns (total 19 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Patient_ID                  6000 non-null   int64
 1   age                         6000 non-null   int64
 2   gender                      6000 non-null   object
 3   bmi                         6000 non-null   float64
 4   blood_pressure              6000 non-null   int64
 5   fasting_glucose_level       6000 non-null   int64
 6   insulin_level               6000 non-null   float64
 7   HbA1c_level                 6000 non-null   float64
 8   cholesterol_level           6000 non-null   int64
 9   triglycerides_level         6000 non-null   int64
 10  physical_activity_level     6000 non-null   object
 11  daily_calorie_intake        6000 non-null   int64
 12  sugar_intake_grams_per_day  6000 non-null   float64
 13  sleep_hours                 6000 non-null   float64
 14  stress_level                6000 non-null   int64
 15  family_history_diabetes     6000 non-null   object
 16  waist_circumference_cm      6000 non-null   float64
 17  diabetes_risk_score         6000 non-null   float64
 18  diabetes_risk_category      6000 non-null   object
dtypes: float64(7), int64(8), object(4)
memory usage: 890.8+ KB

In [4]:
df.columns

Index(['Patient_ID', 'age', 'gender', 'bmi', 'blood_pressure',
       'fasting_glucose_level', 'insulin_level', 'HbA1c_level',
       'cholesterol_level', 'triglycerides_level', 'physical_activity_level',
       'daily_calorie_intake', 'sugar_intake_grams_per_day', 'sleep_hours',
       'stress_level', 'family_history_diabetes', 'waist_circumference_cm',
       'diabetes_risk_score', 'diabetes_risk_category'],
      dtype='object')

In [5]:
df.drop(columns=['Patient_ID'], inplace=True)

In [6]:
df.head()

,age,gender,bmi,blood_pressure,fasting_glucose_level,insulin_level,HbA1c_level,cholesterol_level,triglycerides_level,physical_activity_level,daily_calorie_intake,sugar_intake_grams_per_day,sleep_hours,stress_level,family_history_diabetes,waist_circumference_cm,diabetes_risk_score,diabetes_risk_category
0,77,Female,33.8,154,93,12.1,5.2,242,194,Low,2169,78.4,8.1,4,No,101.1,52.3,Prediabetes
1,54,Male,19.2,123,94,4.6,5.4,212,76,High,1881,16.5,6.6,3,No,60.0,3.7,Low Risk
2,25,Male,33.7,141,150,10.8,6.9,247,221,Low,2811,147.9,6.7,10,Yes,114.7,87.3,High Risk
3,23,Female,32.8,140,145,11.6,6.8,195,193,Low,2826,98.3,4.4,9,Yes,96.6,76.1,High Risk
4,70,Male,33.7,165,90,18.3,5.6,217,170,Moderate,2610,65.8,9.1,5,Yes,107.4,47.7,Prediabetes

In [7]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
age,6000.0,52.230667,18.757508,20.0,36.0,53.00,68.00,84.0
bmi,6000.0,32.939667,7.510155,16.0,26.9,32.75,38.50,50.0
blood_pressure,6000.0,144.482500,17.867248,91.0,132.0,144.00,157.00,200.0
fasting_glucose_level,6000.0,106.105500,31.213994,60.0,87.0,96.00,114.00,281.0
insulin_level,6000.0,15.080333,9.245581,2.0,7.1,13.80,21.00,55.9
HbA1c_level,6000.0,5.784583,0.956614,4.1,5.2,5.50,6.10,11.0
cholesterol_level,6000.0,217.490667,24.888595,139.0,200.0,217.00,234.00,309.0
triglycerides_level,6000.0,177.351500,51.897606,50.0,137.0,173.00,213.00,383.0
daily_calorie_intake,6000.0,2479.547000,548.410642,1200.0,2055.0,2385.00,2848.25,5249.0
sugar_intake_grams_per_day,6000.0,66.555733,39.576891,0.0,35.1,58.30,89.30,255.0
sleep_hours,6000.0,6.998700,1.331378,4.0,6.1,7.10,8.00,10.0
stress_level,6000.0,5.086500,2.342989,1.0,3.0,5.00,7.00,10.0
waist_circumference_cm,6000.0,105.049600,25.079335,60.0,84.7,104.60,124.20,150.0
diabetes_risk_score,6000.0,48.691417,37.242034,0.0,12.9,43.90,88.80,100.0

In [8]:
df.isnull().sum()

age                           0
gender                        0
bmi                           0
blood_pressure                0
fasting_glucose_level         0
insulin_level                 0
HbA1c_level                   0
cholesterol_level             0
triglycerides_level           0
physical_activity_level       0
daily_calorie_intake          0
sugar_intake_grams_per_day    0
sleep_hours                   0
stress_level                  0
family_history_diabetes       0
waist_circumference_cm        0
diabetes_risk_score           0
diabetes_risk_category        0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df['diabetes_risk_category'].unique()

array(['Prediabetes', 'Low Risk', 'High Risk'], dtype=object)

In [11]:
df.head()

,age,gender,bmi,blood_pressure,fasting_glucose_level,insulin_level,HbA1c_level,cholesterol_level,triglycerides_level,physical_activity_level,daily_calorie_intake,sugar_intake_grams_per_day,sleep_hours,stress_level,family_history_diabetes,waist_circumference_cm,diabetes_risk_score,diabetes_risk_category
0,77,Female,33.8,154,93,12.1,5.2,242,194,Low,2169,78.4,8.1,4,No,101.1,52.3,Prediabetes
1,54,Male,19.2,123,94,4.6,5.4,212,76,High,1881,16.5,6.6,3,No,60.0,3.7,Low Risk
2,25,Male,33.7,141,150,10.8,6.9,247,221,Low,2811,147.9,6.7,10,Yes,114.7,87.3,High Risk
3,23,Female,32.8,140,145,11.6,6.8,195,193,Low,2826,98.3,4.4,9,Yes,96.6,76.1,High Risk
4,70,Male,33.7,165,90,18.3,5.6,217,170,Moderate,2610,65.8,9.1,5,Yes,107.4,47.7,Prediabetes

In [12]:
df['age_bin'] = pd.cut(df['age'],bins=[0,30,50,70,100],labels=['young','middle_aged','old','very_old'])

In [13]:
df.drop(columns=['age'], inplace=True)

In [14]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['diabetes_risk_category'] = le.fit_transform(df['diabetes_risk_category'])

In [15]:
df.head()

,gender,bmi,blood_pressure,fasting_glucose_level,insulin_level,HbA1c_level,cholesterol_level,triglycerides_level,physical_activity_level,daily_calorie_intake,sugar_intake_grams_per_day,sleep_hours,stress_level,family_history_diabetes,waist_circumference_cm,diabetes_risk_score,diabetes_risk_category,age_bin
0,Female,33.8,154,93,12.1,5.2,242,194,Low,2169,78.4,8.1,4,No,101.1,52.3,2,very_old
1,Male,19.2,123,94,4.6,5.4,212,76,High,1881,16.5,6.6,3,No,60.0,3.7,1,old
2,Male,33.7,141,150,10.8,6.9,247,221,Low,2811,147.9,6.7,10,Yes,114.7,87.3,0,young
3,Female,32.8,140,145,11.6,6.8,195,193,Low,2826,98.3,4.4,9,Yes,96.6,76.1,0,young
4,Male,33.7,165,90,18.3,5.6,217,170,Moderate,2610,65.8,9.1,5,Yes,107.4,47.7,2,old

In [16]:
df['age'] = le.fit_transform(df['age_bin'])

In [17]:
df.drop(columns=['age_bin'], inplace=True)

In [18]:
df.head()

,gender,bmi,blood_pressure,fasting_glucose_level,insulin_level,HbA1c_level,cholesterol_level,triglycerides_level,physical_activity_level,daily_calorie_intake,sugar_intake_grams_per_day,sleep_hours,stress_level,family_history_diabetes,waist_circumference_cm,diabetes_risk_score,diabetes_risk_category,age
0,Female,33.8,154,93,12.1,5.2,242,194,Low,2169,78.4,8.1,4,No,101.1,52.3,2,2
1,Male,19.2,123,94,4.6,5.4,212,76,High,1881,16.5,6.6,3,No,60.0,3.7,1,1
2,Male,33.7,141,150,10.8,6.9,247,221,Low,2811,147.9,6.7,10,Yes,114.7,87.3,0,3
3,Female,32.8,140,145,11.6,6.8,195,193,Low,2826,98.3,4.4,9,Yes,96.6,76.1,0,3
4,Male,33.7,165,90,18.3,5.6,217,170,Moderate,2610,65.8,9.1,5,Yes,107.4,47.7,2,1

In [19]:
X = df.drop('diabetes_risk_category',axis=1)
y = df['diabetes_risk_category']

In [20]:
numeric_features = X.select_dtypes(include = ['int64','float64']).columns
categorical_features = X.select_dtypes(include = ['object']).columns

In [21]:
numeric_features

Index(['bmi', 'blood_pressure', 'fasting_glucose_level', 'insulin_level',
       'HbA1c_level', 'cholesterol_level', 'triglycerides_level',
       'daily_calorie_intake', 'sugar_intake_grams_per_day', 'sleep_hours',
       'stress_level', 'waist_circumference_cm', 'diabetes_risk_score', 'age'],
      dtype='object')

In [22]:
categorical_features

Index(['gender', 'physical_activity_level', 'family_history_diabetes'], dtype='object')

In [23]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [24]:
from sklearn.base import BaseEstimator, TransformerMixin
import numpy as np

class IQRHandler(BaseEstimator, TransformerMixin):

    def fit(self, X, y=None):
        self.Q1 = np.percentile(X, 25, axis=0)
        self.Q3 = np.percentile(X, 75, axis=0)
        self.IQR = self.Q3 - self.Q1
        return self

    def transform(self, X):
        lower = self.Q1 - 1.5 * self.IQR
        upper = self.Q3 + 1.5 * self.IQR
        return np.clip(X, lower, upper)

In [25]:
numerical_pipe = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('outlier', IQRHandler()),
    ('scaler', StandardScaler())
])

In [26]:
categorical_pipe = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('encoder', OneHotEncoder(handle_unknown='ignore')),
])

In [27]:
combine_pipe = ColumnTransformer(transformers=[
    ('num', numerical_pipe, numeric_features),
    ('cat', categorical_pipe, categorical_features)
]
)

In [28]:
from sklearn.model_selection import train_test_split

In [29]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=42)

In [30]:
X_train_transformed = combine_pipe.fit_transform(X_train)

In [31]:
X_test_transformed = combine_pipe.transform(X_test)

In [32]:
X_train_transformed

array([[-0.14489431,  0.48772886, -0.66291544, ...,  1.        ,
         1.        ,  0.        ],
       [-0.48022879,  0.76807935, -0.44046059, ...,  0.        ,
         1.        ,  0.        ],
       [ 1.03548309,  1.32878032,  1.25019622, ...,  0.        ,
         1.        ,  0.        ],
       ...,
       [ 0.65990846,  0.48772886,  2.18450657, ...,  0.        ,
         1.        ,  0.        ],
       [-0.96311045, -1.19437407, -1.19680706, ...,  0.        ,
         1.        ,  0.        ],
       [-1.37892522, -1.64293485, -0.84087931, ...,  0.        ,
         1.        ,  0.        ]])

In [35]:
X_test_transformed

array([[ 1.54519151,  1.66520091,  2.18450657, ...,  0.        ,
         1.        ,  0.        ],
       [ 0.43188101,  1.16057003, -0.48495156, ...,  0.        ,
         0.        ,  1.        ],
       [ 1.06230985,  2.56232247,  2.18450657, ...,  0.        ,
         1.        ,  0.        ],
       ...,
       [-1.28503156, -0.577603  , -0.84087931, ...,  0.        ,
         1.        ,  0.        ],
       [ 0.15020004,  0.71200925,  1.25019622, ...,  0.        ,
         0.        ,  1.        ],
       [-1.04359073, -1.30651426, -0.97435222, ...,  0.        ,
         1.        ,  0.        ]])

In [37]:
import torch
X_train_tensor = torch.from_numpy(X_train_transformed)
X_test_tensor = torch.from_numpy(X_test_transformed)

In [38]:
type(X_train_tensor)

torch.Tensor

In [39]:
type(X_test_tensor)

torch.Tensor

In [41]:
X_test_tensor.shape[1]

21

In [49]:
class MySimpleNN():
  def __init__(self,X):
    self.weights = torch.randn(X.shape[1],1,dtype=torch.float64,requires_grad=True)
    self.bias = torch.zeros(1,dtype=torch.float64,requires_grad=True)

  def forward(self,X):
    z = torch.matmul(X,self.weights)+self.bias
    y_pred = torch.sigmoid(z)
    return y_pred
  def loss_function(self,y_pred,y):
    #clamp
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred,epsilon,1-epsilon)
    loss = -y*torch.log(y_pred)-(1-y)*torch.log(1-y_pred)
    return loss

In [50]:
model = MySimpleNN(X_test_tensor)

In [51]:
model.weights

tensor([[-0.5839],
        [-0.1405],
        [ 0.9269],
        [-0.0830],
        [ 1.0865],
        [ 0.7052],
        [-0.4460],
        [ 0.1352],
        [-0.3240],
        [ 0.4819],
        [ 0.1915],
        [-1.3962],
        [ 1.5859],
        [-1.0623],
        [ 0.2410],
        [ 0.0918],
        [ 1.6189],
        [-0.4123],
        [ 2.2197],
        [-0.3777],
        [-0.4718]], dtype=torch.float64, requires_grad=True)

In [52]:
model.bias

tensor([0.], dtype=torch.float64, requires_grad=True)